# Semango GoReleaser Configuration
# Author: Omar Kamali <semango@omarkama.li>
# Repository: github.com/omarkamali/semango

version: 2

project_name: semango

before:
  hooks:
    # Build UI before Go build
    - cmd: bash -c "cd ui && yarn install --frozen-lockfile && yarn build"
    - cmd: bash -c "rm -rf internal/api/ui && cp -r ui/dist internal/api/ui"
    # Ensure go.mod is tidy
    - go mod tidy

builds:
  - id: semango
    main: ./cmd/semango
    binary: semango
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      # - windows  # Requires cross-compilation setup for CGO
    goarch:
      - amd64
      - arm64
    ignore:
      # Skip Windows for now due to CGO complexity
      - goos: windows
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

    # Platform-specific build settings
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
          - CGO_LDFLAGS=-L/usr/local/lib -lfaiss_c -lonnxruntime
          - CGO_CPPFLAGS=-I/usr/local/include
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_LDFLAGS=-L/usr/local/lib -lfaiss_c -lonnxruntime
          - CGO_CPPFLAGS=-I/usr/local/include
      - goos: darwin
        goarch: amd64
        env:
          - CC=clang
          - CGO_LDFLAGS=-L/usr/local/lib -lfaiss_c -lonnxruntime
          - CGO_CPPFLAGS=-I/usr/local/include
      - goos: darwin
        goarch: arm64
        env:
          - CC=clang
          - CGO_LDFLAGS=-L/opt/homebrew/lib -lfaiss_c -lonnxruntime
          - CGO_CPPFLAGS=-I/opt/homebrew/include

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/SEMANGO_GUIDE.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🔧 Other"
      order: 999

release:
  github:
    owner: omarkamali
    name: semango
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Semango {{ .Tag }}
    
    Hybrid search engine combining lexical (BM25) and semantic (vector) search.
    
    ### Installation
    
    **macOS / Linux:**
    ```bash
    curl -L "https://github.com/omarkamali/semango/releases/download/{{ .Tag }}/semango_{{ .Version }}_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m).tar.gz" | tar xz
    sudo mv semango /usr/local/bin/
    ```
    
    **Docker:**
    ```bash
    docker pull ghcr.io/omarkamali/semango:{{ .Tag }}
    ```
  footer: |
    ---
    **Full Changelog**: https://github.com/omarkamali/semango/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/omarkamali/semango:{{ .Tag }}"
      - "ghcr.io/omarkamali/semango:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/omarkamali/semango:{{ .Major }}"
      - "ghcr.io/omarkamali/semango:latest"
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Hybrid search engine"
      - "--label=org.opencontainers.image.url=https://github.com/omarkamali/semango"
      - "--label=org.opencontainers.image.source=https://github.com/omarkamali/semango"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--platform=linux/amd64"

# Announce (optional, configure as needed)
# announce:
#   twitter:
#     enabled: false
